### ISSUE TITLE
[Minecraft 1.21.1] Netherman not affected by mobGriefing

### ISSUE THREAD

**Issue by ejektaflex** [Xylonity/Knight-Quest#10]
Netherman (the boss) will add lava and fire to the game world during the boss battle, even if `mobGriefing` is disabled. I'd like to use him for an adventure mode map, but if he is setting things on fire and destroying blocks, then players could find themselves in the basement or the boss room could be burned down. It would be nice if this mob respected the mobGriefing game rule just like the Enderman :)

**Comment by Xylonity** [comment]
Hey! I'm rewriting the Netherman from scratch, including new designs and animations among other things (mainly to give it a new drop that will come in the next version and to fix the problems it had where animations could get stuck or it could move when it shouldn't). I won't be able to release the update until at least the 23nd-24rd because I'm in the middle of final exams, but I'll keep in mind what you said and add it asap! :)

**Comment by ejektaflex** [comment]
Thanks much! I hope to see it on 1.21/1.21.1 :^) but it's nice to hear that it's being worked on!

**Comment by Xylonity** [comment]
Closing this issue as this is fixed. The next major update will be released today
